version: 2.1

orbs:
  python: circleci/python@3.0.0
  aws-cli: circleci/aws-cli@5.1.2
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-ecs: circleci/aws-ecs@6.0.2

executors:
  default-executor:
    docker:
      - image: cimg/base:stable

jobs:
  test:
    executor:
      name: python/default
      tag: "3.12.2"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: test
          command: pytest

  build-and-publish-image:
    executor:
      name: aws-ecr/default
    steps:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: default
          account_id: ${AWS_ACCOUNT_ID}
          repo: watchdog
          dockerfile: Dockerfile
          platform: linux/amd64
          push_image: false
          region: ap-northeast-1
          tag: "2.0"
      - run: docker images
      - aws-ecr/push_image:
          region: ap-northeast-1
          repo: watchdog
          tag: "2.0"

workflows:
  demo:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - build-and-publish-image:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
      - aws-ecs/deploy_service_update:
          requires:
            - build-and-publish-image
          filters:
            branches:
              only:
                - dev
          auth:
            - aws-cli/setup:
                profile_name: default
          cluster: watchdog-cluster
          service_name: watchdog-service
          family: watchdog