version: 2.1

orbs:
  python: circleci/python@3.0.0
  aws-cli: circleci/aws-cli@5.1.2
  aws-ecr: circleci/aws-ecr@9.3.7

executors:
  test-executor:
    docker:
      - image: cimg/openjdk:17.0.13-node

jobs:
  test:
    executor:
      name: python/default
      tag: "3.12.2"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: test
          command: pytest

  build-and-publish-image:
    executor:
      name: aws-ecr/default
    steps:
      - aws-ecr/ecr_login:
          account_id: ${AWS_ACCOUNT_ID}
      - aws-ecr/build_image:
          account_id: ${AWS_ACCOUNT_ID}
          push_image: false
          repo: watchdog
          skip_when_tags_exist: true
          tag: "1.0"
      - run: docker images
      - aws-ecr/push_image:
          region: ap-northeast-1
          repo: watchdog
          tag: "1.0"

workflows:
  demo:
    jobs:
#      - test:
#          filters:
#            branches:
#              only:
#                - main
      - build-and-publish-image:
#          requires:
#            - test
          filters:
            branches:
              only:
                - main